# Generated by Django 6.1 on 2026-10-01 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoracul_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Изменение'), ('add', 'Добавление записей')], default='view', max_length=10, verbose_name='Уровень доступа')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение от ветеринара')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_access_requests', to='vetoracul_app.pet', verbose_name='Питомец')),
                ('vet', models.ForeignKey(limit_choices_to={'role': 'vet'}, on_delete=django.db.models.deletion.CASCADE, related_name='vet_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ветеринар')),
            ],
            options={
                'verbose_name': 'Заявка на доступ',
                'verbose_name_plural': 'Заявки на доступ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Изменение'), ('add', 'Добавление записей')], default='view', max_length=10, verbose_name='Уровень доступа')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_accesses', to='vetoracul_app.pet', verbose_name='Питомец')),
                ('vet', models.ForeignKey(limit_choices_to={'role': 'vet'}, on_delete=django.db.models.deletion.CASCADE, related_name='vet_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Ветеринар')),
            ],
            options={
                'verbose_name': 'Доступ ветеринара',
                'verbose_name_plural': 'Доступы ветеринаров',
                'ordering': ['-granted_at'],
                'unique_together': {('vet', 'pet')},
            },
        ),
    ]
