# Generated by Django 6.1 on 2026-10-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoracul_app', '0003_document_deleted_at_document_is_deleted_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный доступ'),
        ),
        migrations.AddField(
            model_name='document',
            name='share_token',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='Токен публичной ссылки'),
        ),
    ]
