# Generated by Django 6.1 on 2026-10-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoracul_app', '0003_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления на почту'),
        ),
    ]
