# Generated by Django 6.1 on 2026-10-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoracul_app', '0004_document_is_public_document_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='notified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Когда отправлено уведомление'),
        ),
    ]
