# Generated by Django 6.1 on 2026-10-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetoracul_app', '0004_user_notify_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notify_news',
        ),
    ]
