# Generated by Django 6.1 on 2026-10-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoracul_app', '0005_reminder_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='pet',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Здоров'), ('observation', 'Под наблюдением'), ('treatment', 'На лечении'), ('recovery', 'Восстановление'), ('chronic', 'Хроническое заболевание'), ('critical', 'Критическое состояние'), ('quarantine', 'Карантин')], default='healthy', max_length=20, verbose_name='Состояние здоровья'),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
