# Generated by Django 6.1 on 2026-10-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoracul_app', '0005_vetinvitetoken_vetprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notify_news',
            field=models.BooleanField(default=False, verbose_name='СНовости и обновления'),
        ),
    ]
