# Generated by Django 6.1 on 2026-10-06 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoracul_app', '0005_remove_user_notify_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('note', models.CharField(blank=True, help_text='Например: «Иванов И.И., МГАВМиБ, рекомендован Петровой А.»', max_length=200, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использована')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vet_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
            ],
            options={
                'verbose_name': 'Приглашение ветеринара',
                'verbose_name_plural': 'Приглашения ветеринаров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('therapist', 'Терапевт'), ('surgeon', 'Хирург'), ('oncologist', 'Онколог-гематолог'), ('cardiologist', 'Кардиолог'), ('neurologist', 'Невролог'), ('dermatologist', 'Дерматолог'), ('ophthalmologist', 'Офтальмолог'), ('dentist', 'Стоматолог'), ('rehabilitologist', 'Реабилитолог'), ('exotic', 'Специалист по экзотическим животным')], max_length=50, verbose_name='Специализация')),
                ('education', models.CharField(max_length=200, verbose_name='Образование (вуз)')),
                ('grad_year', models.IntegerField(verbose_name='Год окончания')),
                ('license_number', models.CharField(max_length=50, verbose_name='Номер лицензии')),
                ('experience', models.IntegerField(verbose_name='Стаж (лет)')),
                ('clinic', models.CharField(max_length=200, verbose_name='Место работы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vet_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль ветеринара',
                'verbose_name_plural': 'Профили ветеринаров',
            },
        ),
    ]
